term.setTextColor(colors.yellow)
print("LinuCraft 6.1.0-2712 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64")
print("")
print("The programs included with the Debian GNU/LinuCraft system are free software;")
print("")
print("Debian GNU/LinuCraft comes with ABSOLUTELY NO WARRANTY, to the extentpermitted by applicable law.")
term.setTextColor(colors.white)
