local help = {
    "----HELP-----",
    "ABOUT // About this OS.",
    "CD // Displays the name of or changes the current.",
    "directory.",
    "",
    "DELETE // Deletes one or more files.",
    "EJECT // Ejects any item currently in the drive.",
    "HELP // Provides Help information for commands.",
    "LABEL // Renames the computer.",
    "USER // Changes the current username.",
    "MKDIR // Creates a directory.",
    "MOVE // Moves one or more files from one directory ",
    "to another directory.",
    "",
    "PAINT // Basic graphic editor to make images.",
    "IMAGEVIEWER // View images on computer.",
    "REBOOT // Shuts down and turns on the computer.",
    "SET // Changes default system settings.",
    "TIME // Display the current date and time.",
    "ALIAS //  Shows all the alias of commands.",
    "CLEAR // Clears the terminal.",
    "DRIVE // Display drive information.",
    "",
    "EXIT // Exits the current program.",
    "ID // Prints the computer ID.",
    "LIST // Shows the files in the current directory.",
    "MONITOR // Sets up the monitor.",
    "PERIPHERALS // Sets up a peripheral.",
    "REDSTONE // Sets up redstone. (?)",
    "SHELL // Starts CraftOS shell.",
    "",
    "TYPE // Print the type of file",
    "APIS // List all of the default apis.",
    "COPY // Copies a file.",
    "EDIT // Edits a file.",
    "GPS // Retrieves computer/turtle location. (API)",
    "IMPORT // Used to import an API.",
    "LUA // Opens a lua 'shell'",
    "",
    "MOTD // Useless tips lmfao",
    "PROGRAMS // List all the programs.",
    "RENAME // Renames a file/folder.",
    "SHUTDOWN // Shutdowns the computer."
}

textutils.pagedTabulate(help)
